#!/bin/bash

# ------------------------------------------------------------------------------
# Update front controller with Dotenv and new path configuration.
# ------------------------------------------------------------------------------

tail -n +5 public/index.php >> index
mv index public/index.php

# ------------------------------------------------------------------------------
# Create .env file
# ------------------------------------------------------------------------------

cat > .env <<EOL
DB_HOST=localhost
DB_NAME=
DB_USER=
DB_PASS=
EOL

# ------------------------------------------------------------------------------
# Add paths to .gitignore
# ------------------------------------------------------------------------------

touch .gitignore
echo '.env' >> .gitignore

# ------------------------------------------------------------------------------
# Add environment variables to config/db.php
# ------------------------------------------------------------------------------

sed -i.bak "s/.*'server'.*/    'server' => getenv('DB_HOST'),/" config/db.php
sed -i.bak "s/.*'database'.*/    'database' => getenv('DB_NAME'),/" config/db.php
sed -i.bak "s/.*'user'.*/    'user' => getenv('DB_USER'),/" config/db.php
sed -i.bak "s/.*'password'.*/    'password' => getenv('DB_PASS'),/" config/db.php

rm config/db.php.bak
